plugins {
    id("java-library")
    id("net.minecraftforge.gradle") version "[6.0.40,6.1)"
}

base {
    archivesName = "authsuite-forge"
}

java {
    toolchain.languageVersion = JavaLanguageVersion.of(21)
}

minecraft {
    mappings channel: "official", version: "${minecraft_version_1_19_4}"

    runs {
        configureEach {
            workingDirectory = layout.projectDirectory.dir("run")
            property("forge.logging.markers", "REGISTRIES")
            property("forge.logging.console.level", "debug")
            args("--mixin.config=authsuite.mixins.json")

            mods {
                "authsuite" {
                    source(sourceSets.main)
                }
            }
        }
        register("client")
        register("server") {
            args("--nogui")
        }
    }
}

repositories {
    mavenCentral()
}

dependencies {
    implementation(project(":authsuite-common"))
    minecraft "net.minecraftforge:forge:${forge_version_1_19_4}"
    implementation("com.google.code.gson:gson:2.10.1")
    implementation("org.yaml:snakeyaml:2.2")
    annotationProcessor("org.spongepowered:mixin:0.8.7:processor")
    implementation("org.spongepowered:mixin:0.8.7")
}

processResources {
    inputs.property("version", project.version)
    filesMatching("META-INF/mods.toml") {
        expand(
                "version": project.version,
                "mod_id": project.property("mod_id"),
                "minecraft_version": project.property("minecraft_version_1_19_4")
        )
    }
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = "UTF-8"
    options.release = 17
}

jar {
    manifest {
        attributes["MixinConfigs"] = "authsuite.mixins.json"
    }
}